global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

 - job_name: 'temporalmetrics'
   metrics_path: /metrics
   scheme: http
   static_configs:
     # Temporal Service metrics target
     - targets:
         - targets: ['${TEMPORAL_SCRAPE_PRIVATE_DOMAIN}:${TEMPORAL_SCRAPE_PORT}']
       labels:
         group: 'server-metrics'

     # # Local app targets (if configured)
     # - targets:
     #     - 'host.docker.internal:8077'
     #     - 'host.docker.internal:8078'
     #   labels:
     #     group: 'sdk-metrics'


  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE
